#!/usr/bin/env python3
import sys

from map_lib.eufs_track_generator.track_generator_gui import EUFSTracksGUI
from rqt_gui.main import Main

plugin = 'EUFSTracksGUI'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))