# NOTE: This data is not correct, it is based on sketchy calculations

inertia:
  m:        300.0      # Weight of the Vehicle [kg]
  g:        9.81       # Gravity force         [m/s^2]
  I_z:      172.44     # Inertial force I_z

kinematic:
  l: 1.53              # Vehicle Length [m]
  w_front: 0.5         # Fraction of weight front
  axle_width: 1.2

tyre:
  A: 1.0
  B: 1.4
  C: 12.56
  radius: 0.2525
  rolling_resistance: 0.02

powertrain:
  overdrive: 0.01

steering:
  max_rate: 0.39
  max_angle: 0.384

aero:
  C_down: 0.3         # F_Downforce = C_Downforce*v_x^2
  C_drag: 0.5         # F_Drag = C_Drag*v_x^2

input_ranges:
  acceleration:
    max: 5.2
    min: -5.2
  velocity:
    max: 30.0
    min: 0.0
  steering:
    max: 0.37
    min: -0.37
